### ISSUE TITLE
bicamon/db/seeds/cells.csvはどこからのAPIですか？

### ISSUE THREAD

**Issue by suricata3838** [kiyomaro927/bicamon#70]
cells.csvの中のデータベースの数を増やしたいと思うのですが、
こちらはどこかのAPIなどを参考に作られたものでしょうか？
cells.csvのE,F,G列は３Dでの座標だと思うのですが、
C列は何ですか？何かのVolumeですか？
Allen brain Atlasのウェブサイトでこちらのデータが何のデータなのか探してみたのですが、
わかりませんでした。

ご回答よろしくお願いいたします。

**Comment by kiyomaro927** [comment]
ご質問ありがとうございます。説明を残していなくて本当にすいません。
`cells.csv`の各カラムは以下の情報を表しています。

* Acronym (セルの略語)
* Name (セルの名前)
* Major Region (セルが属している領野)
* Voxel Count (セルの大きさ)
* X (x座標)
* Y (y座標)
* Z (z座標)

これらのデータは、[AllenSDK](http://alleninstitute.github.io/AllenSDK/)及び[A mesoscale connectome of the mouse brain[Oh et al., 2014]](https://www.nature.com/nature/journal/v508/n7495/full/nature13186.html)にて公開されているデータから取得しています。
特に質問のVoxel Countの点については、[こちらのエクセルファイル](http://www.nature.com/nature/journal/v508/n7495/extref/nature13186-s2.xlsx)のSheet2のVoxel Countのカラムの値を使用しています。
また、[Acronym, x, y, z]をAllenSDKから取得するスクリプトが[getcoordinates](https://github.com/kiyomaro927/getcoordinates)にあります。データベース作成の参考にしていただけると幸いです。（先ほど少しだけきれいにしておきました。）
